name = "MetaRange"
uuid = "a63c7f9e-ebbd-451a-8f08-4fd47d716cbd"
authors = ["janablechschmidt <jana.blechschmidt@uni-wuerzburg.de", "rroelz <robin.roelz@gmail.com>"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
